# Generated by Django 5.2.5 on 2025-08-11 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Дата торгового дня')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale', 'Продажа'), ('return', 'Возврат'), ('other', 'Другое')], max_length=20, verbose_name='Тип события')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время события')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('trading_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trading_day.tradingday', verbose_name='Торговый день')),
            ],
        ),
    ]
