# Generated by Django 5.2.5 on 2025-08-11 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поставки')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('status', models.CharField(choices=[('partial', 'Частично получено'), ('over', 'Переполучено'), ('full', 'Полностью получено'), ('extra', 'Экстра')], editable=False, max_length=20, verbose_name='Статус')),
                ('extra_shipment', models.BooleanField(default=False, verbose_name='Экстра поставка')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('supplier', models.CharField(editable=False, max_length=255, verbose_name='Поставщик')),
                ('customer', models.CharField(editable=False, max_length=255, verbose_name='Покупатель')),
                ('request_date', models.DateField(editable=False, verbose_name='Дата заявки')),
                ('extra_request', models.BooleanField(editable=False, verbose_name='Экстра заявка')),
                ('price_per_unit', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена за единицу')),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='goods.product', verbose_name='Товар')),
                ('request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='request.requestitem', verbose_name='Позиция заявки')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
