# Generated by Django 5.2.5 on 2025-08-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('candidate', 'Кандидат на заявку'), ('in_request', 'В заявке'), ('extra', 'В заявке экстра')], default='candidate', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу')),
                ('supplier', models.CharField(default='неизвестный поставщик', max_length=255, verbose_name='Поставщик')),
                ('customer', models.CharField(default='покупатель', max_length=255, verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='goods.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='request.request', verbose_name='Заявка')),
            ],
        ),
    ]
