# Generated by Django 5.2.5 on 2025-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='delivered_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Количество уже поставленных единиц', verbose_name='Поставлено'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Заявка полностью выполнена', verbose_name='Выполнено'),
        ),
    ]
