# Generated by Django 5.2.5 on 2025-08-11 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Серийный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='delivery.delivery', verbose_name='Поставка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Единица товара',
                'verbose_name_plural': 'Единицы товара',
            },
        ),
    ]
