# Generated by Django 5.2.5 on 2025-08-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Единица товара', 'verbose_name_plural': 'Единицы товара'},
        ),
        migrations.AlterField(
            model_name='productunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='goods.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='serial_number',
            field=models.CharField(editable=False, help_text='Автоматически генерируется при создании', max_length=100, unique=True, verbose_name='Серийный номер'),
        ),
    ]
