# Generated by Django 5.2.5 on 2025-08-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading_day', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена продажи')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='trading_day.event', verbose_name='Событие')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.productunit', verbose_name='Карточка товара')),
            ],
        ),
    ]
