# Generated by Django 5.2.5 on 2025-08-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
        ('trading_day', '0001_initial'),
        ('unit', '0002_alter_productunit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='trading_day.event'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.productunit'),
        ),
    ]
